name: Incremental Sync to Notion

on:
  # Trigger manually
  workflow_dispatch:
  # Trigger on a schedule (e.g., daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'

jobs:
  incremental-sync:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Cache last-sync.json file
      - name: Cache last-sync.json
        id: cache-last-sync
        uses: actions/cache@v3
        with:
          path: last-sync.json
          key: last-sync-cache

      # Initialize last-sync.json if cache is not hit
      - name: Initialize last-sync.json if not cached
        if: steps.cache-last-sync.outputs.cache-hit != 'true'
        run: |
          LAST_SYNC_TIME=$(date -u -d "-1 day" +"%Y-%m-%dT%H:%M:%S.000Z")
          echo "{\"lastSyncTime\": \"$LAST_SYNC_TIME\"}" > last-sync.json

      # Set environment variables
      - name: Load environment variables
        run: |
          echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> $GITHUB_ENV
          echo "NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}" >> $GITHUB_ENV

      # Run the incremental sync script
      - name: Run incremental sync
        run: npm run incremental-sync